CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY  DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    phone_number  VARCHAR(16) NOT NULL, 
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);